; ============================================================
;  DYN-200 — Couple-mètre MODBUS RTU via RS485 (MAX485)
;  Plateforme : Arduino Mega 2560
; ============================================================

[env:megaatmega2560]
platform  = atmelavr
board     = megaatmega2560
framework = arduino

; Dépendances
lib_deps =
    4-20ma/ModbusMaster @ ^2.0.1    ; Librairie ModbusMaster (robuste, légère, RTU)

monitor_speed = 115200
upload_speed  = 115200
